// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
namespace CryptoTests
{
    [TestFixture]
    public class CryptoNameSymbolTest
    {
        private IWebDriver driver;
        public IDictionary<string, object> vars { get; private set; }
        private IJavaScriptExecutor js;
        [SetUp]
        public void SetUp()
        {
            driver = new ChromeDriver();
            js = (IJavaScriptExecutor)driver;
            vars = new Dictionary<string, object>();
        }
        [TearDown]
        protected void TearDown()
        {
            driver.Quit();
        }
        [Test]
        [TestCase("Bitcoin", "BTC")]
        [TestCase("Bitcoin", "")]
        [TestCase("", "BTC")]
        [TestCase("Bit", "BT")]
        public void TestCryptoNameSymbol(string crName, string crSymbol)
        {
            driver.Navigate().GoToUrl("http://127.0.0.1:5500/");
            driver.Manage().Window.Size = new System.Drawing.Size(1536, 816);
            driver.FindElement(By.Id("nameInput")).SendKeys(crName);
            driver.FindElement(By.Id("symbolInput")).SendKeys(crSymbol);
            driver.FindElement(By.CssSelector(".el:nth-child(1)")).Click();
            driver.Close();
        }
    }
}