// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;

namespace MatrixTests
{
    [TestFixture]
    public class FirstTest
    {
        private IWebDriver driver;
        public IDictionary<string, object> vars { get; private set; }
        private IJavaScriptExecutor js;
        [SetUp]
        public void SetUp()
        {
            driver = new ChromeDriver();
            js = (IJavaScriptExecutor)driver;
            vars = new Dictionary<string, object>();
        }
        [TearDown]
        protected void TearDown()
        {
            driver.Quit();
        }

        //[Test]
        //[TestCase(new double[] {1, 2,3,4,5,6,7,8,9})]
        //[TestCase(new double[] {10, 20,30,40,50,60,70,80,90})]
        //[TestCase(new double[] {5, 10,50,4,15,96,17,35,38})]
        public void first(double[] a)
        {
            driver.Navigate().GoToUrl("https://matrixcalc.org/");
            driver.Manage().Window.Size = new System.Drawing.Size(1536, 739);
            driver.FindElement(By.Id("A-0-0")).Click();
            driver.FindElement(By.Id("A-0-0")).SendKeys(a[0].ToString());
            driver.FindElement(By.Id("A-0-1")).SendKeys(a[1].ToString());
            driver.FindElement(By.Id("A-0-2")).SendKeys(a[2].ToString());
            driver.FindElement(By.Id("A-1-0")).SendKeys(a[3].ToString());
            driver.FindElement(By.Id("A-1-1")).SendKeys(a[4].ToString());
            driver.FindElement(By.Id("A-1-2")).SendKeys(a[5].ToString());
            driver.FindElement(By.Id("A-2-0")).SendKeys(a[6].ToString());
            driver.FindElement(By.Id("A-2-1")).SendKeys(a[7].ToString());
            driver.FindElement(By.Id("A-2-2")).SendKeys(a[8].ToString());
            driver.FindElement(By.Id("B-0-0")).Click();
            driver.FindElement(By.Id("B-0-0")).SendKeys("2");
            driver.FindElement(By.Id("B-0-1")).SendKeys("4");
            driver.FindElement(By.Id("B-0-2")).SendKeys("6");
            driver.FindElement(By.Id("B-1-0")).SendKeys("8");
            driver.FindElement(By.Id("B-1-1")).SendKeys("10");
            driver.FindElement(By.Id("B-1-2")).SendKeys("12");
            driver.FindElement(By.Id("B-2-0")).SendKeys("14");
            driver.FindElement(By.Id("B-2-1")).SendKeys("16");
            driver.FindElement(By.Id("B-2-2")).SendKeys("18");
            driver.FindElement(By.XPath("//div[@id=\'right\']/main/form/div[2]/div/button")).Click();
            driver.Close();
        }
    }
}