// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;

namespace MatrixTests
{

    [TestFixture]
    public class SecondTest
    {
        private IWebDriver driver;
        public IDictionary<string, object> vars { get; private set; }
        private IJavaScriptExecutor js;
        [SetUp]
        public void SetUp()
        {
            driver = new ChromeDriver();
            js = (IJavaScriptExecutor)driver;
            vars = new Dictionary<string, object>();
        }
        [TearDown]
        protected void TearDown()
        {
            driver.Quit();
        }
        //[Test]
        public void second()
        {
            driver.Navigate().GoToUrl("https://matrixcalc.org/");
            driver.Manage().Window.Size = new System.Drawing.Size(1554, 834);
            driver.FindElement(By.CssSelector(".tdmatrix:nth-child(1) .decrement-size-button")).Click();
            driver.FindElement(By.CssSelector(".tdmatrix:nth-child(3) .decrement-size-button")).Click();
            driver.FindElement(By.Id("A-0-0")).Click();
            driver.FindElement(By.Id("A-0-0")).SendKeys("1");
            driver.FindElement(By.Id("A-0-1")).SendKeys("2");
            driver.FindElement(By.Id("A-1-0")).SendKeys("3");
            driver.FindElement(By.Id("A-1-1")).SendKeys("4");
            driver.FindElement(By.Id("B-0-0")).Click();
            driver.FindElement(By.Id("B-0-0")).SendKeys("5");
            driver.FindElement(By.Id("B-0-1")).SendKeys("6");
            driver.FindElement(By.Id("B-1-0")).SendKeys("7");
            driver.FindElement(By.Id("B-1-1")).SendKeys("8");
            driver.FindElement(By.CssSelector(".bbox2 .expression-button:nth-child(1)")).Click();
            driver.Close();
        }
    }
}